name: Update Config

on:
  workflow_dispatch:
jobs:
  build:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false
        if: startsWith(matrix.os, 'windows')

      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B formatter:validate verify --file pom.xml
      - name: Copy Configuration
        run: |
           rm -rf docs/config
           cp -r target/asciidoc/generated/config docs/
           git add docs/config
           git commit -m "doc: Update config documentation"
      - name: Push Configuration
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{github.base_ref}}
          force: true
